# Site settings
title: "PiP Planner Application"
description: "Comprehensive Investment Planning Tool - Manage your finances effectively."
<<<<<<< HEAD
baseurl: "/docs"
=======
baseurl: "/docs"
>>>>>>> cf2f73f0fa4070dd33910f4f17ebf9046f3d8619
url: "https://nawrashaswia.github.io"

# Language-specific settings
defaults:
  - scope:
      path: "en"
    values:
      lang: "en"
      permalink: /en/:path/
  - scope:
      path: "ar"
    values:
      lang: "ar"
      permalink: /ar/:path/

include:
  - search.json

# Navbar links
nav_links:
  - name: Home
    link: "/"
  - name: Contents
    link: "/docs/introduction.html"
  - name: YouTube
    link: "https://www.youtube.com/your-channel"
  - name: Download PiP Planner
    link: "/download.html"
  - name: About PiP
    link: "/about.html"
  - name: Contact Me
    link: "/contact.html"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
  - jekyll-paginate
  - jekyll-analytics

# SEO and Social Media settings
seo:
  title: "PiP Planner"
  description: "Comprehensive Investment Planning Tool"
  author: "Nawras Haswia"
  twitter:
    username: "your_twitter_username"
  facebook:
    publisher: "your_facebook_page_url"

exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/

markdown: kramdown
highlighter: rouge

permalink: /:categories/:title/
paginate: 10

# Google Analytics
google_analytics: UA-XXXXXXXX-X
