# Site settings
title: "CIPT Application"
description: "Comprehensive Investment Planning Tool - Manage your finances effectively."
baseurl: "/CIPT" 
url: "https://nawrashaswia.github.io" 
include:
  - search.json
lang: en


# Navbar links
nav_links:
  - name: Home
    link: "/"
  - name: Contents
    link: "/docs/introduction.html"
  - name: YouTube
    link: "https://www.youtube.com/your-channel"
  - name: Download CIPT
    link: "/download.html"
  - name: About CIPT
    link: "/about.html"
  - name: Contact Me
    link: "/contact.html"

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-feed
 
 

# SEO and Social Media settings
seo:
  title: "CIPT Application"
  description: "Comprehensive Investment Planning Tool"
  author: "Nawras"
  twitter:
    username: your_twitter_username # Your Twitter username
  facebook:
    publisher: your_facebook_page_url # Your Facebook page URL

# Exclude these files from the sitemap
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/


# Other settings
markdown: kramdown
highlighter: rouge

# Permalinks
permalink: pretty
permalink: /:categories/:title/


